### ISSUE TITLE
Inconsistency in Error

### ISSUE THREAD

**Issue by franko4don** [NwangwuOsitadinma/gateman#10]
Some functions like `async disallow(claimName)` throw this error
`throw new Error({
      message: "The claim does not exist. Consider creating it first"
  });`
while all others throw this one 
`throw new Error('Error message');`

**Comment by ibesoft11** [comment]
@franko4don We're currently working on a fix for this, thanks for pointing it out :)

**Comment by NwangwuOsitadinma** [comment]
@franko4don, we have fixed this issue
